import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from datetime import datetime, timedelta

# === PAGE CONFIGURATION ===
st.set_page_config(layout="wide", page_title="TradeView Pro")

# === CSS ===
st.markdown("""
<style>
    .stApp { background-color: #0a192f; }
    
    /* Metrics Styling */
    div[data-testid="stMetric"] {
        background-color: #112240;
        padding: 15px;
        border-radius: 10px;
        border: 1px solid #233554;
        box-shadow: 0 4px 6px rgba(0,0,0,0.3);
    }
    div[data-testid="stMetricLabel"] { color: #8892b0 !important; }
    div[data-testid="stMetricValue"] { color: #e6f1ff !important; font-family: 'monospace'; }
    
    /* Sidebar */
    section[data-testid="stSidebar"] { background-color: #112240; }
    .stTextInput>div>div>input { color: #e6f1ff; }
    
    /* Tabs */
    button[data-baseweb="tab"] {
        background-color: transparent !important;
        color: #8892b0 !important;
        font-weight: 600;
    }
    button[data-baseweb="tab"][aria-selected="true"] {
        color: #64ffda !important;
        border-bottom: 2px solid #64ffda !important;
    }
    
    /* Disclaimer Box */
    .disclaimer {
        font-size: 0.8rem; 
        color: #8892b0; 
        background-color: #1e2329; 
        padding: 10px; 
        border-radius: 5px; 
        border-left: 3px solid #ff5f5f;
    }
</style>
""", unsafe_allow_html=True)

# === SIDEBAR ===
st.sidebar.header("📊 Asset Selection")
ticker = st.sidebar.text_input("Primary Ticker", value="BPOP").upper()
comp_ticker = st.sidebar.text_input("Compare Against", value="FBP").upper()

st.sidebar.header("⚙️ Timeframe")
days = st.sidebar.number_input("Lookback Period (Days)", 30, 3650, 365, 30)

# === LEGAL DISCLAIMER ===
st.sidebar.markdown("---")
st.sidebar.markdown("""
<div class="disclaimer">
    <strong>⚠️ LEGAL DISCLAIMER</strong><br>
    This dashboard is for <strong>educational and research purposes only</strong>. 
    The forecasts and indicators are generated by mathematical models (Linear Regression) and do not constitute financial advice. 
    <br><br>
    Past performance is not indicative of future results. Trade at your own risk.
</div>
""", unsafe_allow_html=True)

st.title(f"📈 TradeView: {ticker} vs {comp_ticker}")

# === DATA ENGINE ===
@st.cache_data(ttl=3600)
def get_data(symbol, period_days):
    try:
        stock = yf.Ticker(symbol)
        start_date = datetime.today() - timedelta(days=period_days)
        df = stock.history(start=start_date, end=datetime.today())
        if df.empty: return None
        df.index = df.index.tz_localize(None)
        return df
    except Exception as e:
        return None

# === FINANCIAL LOGIC ===
def calculate_rsi(data, window=14):
    delta = data['Close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=window).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=window).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))

def calculate_bollinger(data, window=20):
    sma = data['Close'].rolling(window=window).mean()
    std = data['Close'].rolling(window=window).std()
    upper = sma + (std * 2)
    lower = sma - (std * 2)
    return upper, lower

# Fetch Data
df1 = get_data(ticker, days)
df2 = get_data(comp_ticker, days) if comp_ticker else None

if df1 is not None and not df1.empty:
    try:
        # Pre-Calculate Indicators for Primary
        df1['SMA_50'] = df1['Close'].rolling(window=50).mean()
        df1['RSI'] = calculate_rsi(df1)
        df1['BB_Upper'], df1['BB_Lower'] = calculate_bollinger(df1)

        # --- HEADLINE METRICS (Primary) ---
        curr_price = float(df1['Close'].iloc[-1])
        delta = float(curr_price - df1['Close'].iloc[-2])
        volatility = float(df1['Close'].pct_change().std() * 100 * (252**0.5))
        
        c1, c2, c3, c4 = st.columns(4)
        c1.metric(f"{ticker} Price", f"${curr_price:.2f}", f"{delta:.2f}")
        c2.metric("Volatility", f"{volatility:.2f}%")
        c3.metric("RSI (14-Day)", f"{float(df1['RSI'].iloc[-1]):.1f}")
        
        if df2 is not None:
            comp_price = float(df2['Close'].iloc[-1])
            comp_delta = float(comp_price - df2['Close'].iloc[-2])
            c4.metric(f"{comp_ticker} Price", f"${comp_price:.2f}", f"{comp_delta:.2f}")
        else:
            c4.metric("Volume", f"{int(df1['Volume'].iloc[-1]):,}")

        # === TABS UI ===
        tab1, tab2, tab3, tab4 = st.tabs(["⚔️ Comparison", "📉 Price Action", "📊 Technicals", "🤖 AI Forecast"])

        # TAB 1: COMPARISON
        with tab1:
            if df2 is not None:
                st.subheader(f"Relative Performance: {ticker} vs {comp_ticker}")
                
                # Normalize Data to Percentage Return
                df1['Return'] = (df1['Close'] / df1['Close'].iloc[0] - 1) * 100
                df2['Return'] = (df2['Close'] / df2['Close'].iloc[0] - 1) * 100
                
                comp_fig = go.Figure()
                comp_fig.add_trace(go.Scatter(x=df1.index, y=df1['Return'], name=ticker, line=dict(color='#64ffda', width=2)))
                comp_fig.add_trace(go.Scatter(x=df2.index, y=df2['Return'], name=comp_ticker, line=dict(color='#ff0055', width=2)))
                
                comp_fig.update_layout(title=f"Cumulative Return (%) over {days} Days", yaxis_title="Return (%)", template="plotly_dark", height=500, paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
                st.plotly_chart(comp_fig, use_container_width=True)
                
                common_dates = df1.index.intersection(df2.index)
                correlation = df1['Close'][common_dates].corr(df2['Close'][common_dates])
                st.info(f"ℹ️ Correlation Coefficient: **{correlation:.2f}**. (1.0 = Move together, -1.0 = Move opposite)")
            else:
                st.warning(f"Could not load data for comparison ticker: {comp_ticker}")

        # TAB 2: PRICE ACTION
        with tab2:
            fig = go.Figure()
            fig.add_trace(go.Candlestick(x=df1.index, open=df1['Open'], high=df1['High'], low=df1['Low'], close=df1['Close'], name='Price'))
            fig.add_trace(go.Scatter(x=df1.index, y=df1['SMA_50'], line=dict(color='#64ffda', width=1), name='SMA 50'))
            fig.update_layout(title=f"{ticker} Price History", yaxis_title="USD", template="plotly_dark", height=500, paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
            st.plotly_chart(fig, use_container_width=True)

        # TAB 3: TECHNICALS
        with tab3:
            col_t1, col_t2 = st.columns(2)
            with col_t1:
                bfig = go.Figure()
                bfig.add_trace(go.Scatter(x=df1.index, y=df1['Close'], line=dict(color='#e6f1ff', width=1), name='Price'))
                bfig.add_trace(go.Scatter(x=df1.index, y=df1['BB_Upper'], line=dict(color='rgba(100, 255, 218, 0.5)', width=1), name='Upper'))
                bfig.add_trace(go.Scatter(x=df1.index, y=df1['BB_Lower'], line=dict(color='rgba(100, 255, 218, 0.5)', width=1), name='Lower', fill='tonexty'))
                bfig.update_layout(title="Bollinger Bands", template="plotly_dark", height=400, paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
                st.plotly_chart(bfig, use_container_width=True)
            with col_t2:
                rfig = go.Figure()
                rfig.add_trace(go.Scatter(x=df1.index, y=df1['RSI'], line=dict(color='#fee440', width=2), name='RSI'))
                rfig.add_hline(y=70, line_dash="dash", line_color="red")
                rfig.add_hline(y=30, line_dash="dash", line_color="green")
                rfig.update_layout(title="RSI (Momentum)", template="plotly_dark", height=400, yaxis_range=[0,100], paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
                st.plotly_chart(rfig, use_container_width=True)

        # TAB 4: AI FORECAST
        with tab4:
            st.subheader(f"AI Trend Projection: {ticker}")
            
            # Prepare Data
            df1['Numbers'] = list(range(0, len(df1)))
            X = np.array(df1['Numbers'])
            y = np.array(df1['Close'])
            
            # Linear Regression
            z = np.polyfit(X, y, 1)
            p = np.poly1d(z)
            
            # Forecast
            future_days = 30
            last_x = X[-1]
            future_X = np.arange(last_x, last_x + future_days)
            future_dates = [df1.index[-1] + timedelta(days=i) for i in range(1, future_days + 1)]
            forecast_y = p(future_X)

            ffig = go.Figure()
            ffig.add_trace(go.Scatter(x=df1.index, y=df1['Close'], name='Historical', line=dict(color='#8892b0', width=1)))
            ffig.add_trace(go.Scatter(x=future_dates, y=forecast_y, name='AI Forecast (30 Days)', line=dict(color='#ff0055', width=3, dash='dot')))
            ffig.update_layout(title="Linear Regression Trend", template="plotly_dark", height=500, paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
            st.plotly_chart(ffig, use_container_width=True)
            
            st.info("ℹ️ Note: This projection uses a Linear Regression model (Ordinary Least Squares) based on the selected timeframe. It assumes the current trend continues linearly.")

    except Exception as e:
        st.error(f"Calculation Error: {e}")

else:
    st.warning(f"No data found for {ticker}")
